@hostname = localhost
@port = 20736
@host = {{hostname}}:{{port}}
@path = discord/
@contentType = application/json
@authToken = EZr7BmzOkypM3aRZSY9FHTTXo5QvhxLW

### Sample POST with authorization

POST http://{{host}}/{{path}} HTTP/1.1
Authorization: {{authToken}}

{
   "command": "status"
}

### Sample POST without authorization

POST http://{{host}}/{{path}} HTTP/1.1

{
   "command": "status"
}

### Sample POST with invalid authorization

POST http://{{host}}/{{path}} HTTP/1.1
Authorization: Not exactly authorized..

{
   "command": "status"
}

### Sample POST with invalid JSON body

POST http://{{host}}/{{path}} HTTP/1.1
Authorization: {{authToken}}

{
   "command": "chat",
   data: "something value"
}

### Sample POST for chat command

POST http://{{host}}/{{path}} HTTP/1.1
Authorization: {{authToken}}

{
   "command": "chat",
   "data": {
       "username": "Chad",
       "content": "Hello world!"
   }
}