site_name: Valheim Discord Connector
repo_url: https://github.com/nwesterhausen/valheim-discordconnector
theme:
  name: "material"
  locale: "en"
  font:
    text: Source Sans Pro
    code: IBM Plex Mono
  features:
    - navigation.sections
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

docs_dir: docs
site_dir: bin/mkdocs
strict: true

nav:
  - index.md
  - changelog.md
  - Installation:
    - webhook-instructions.md
  - Configuration:
    - editing-configuration.md
    - randomized-messages.md
    - configuration-details.md
  - API:
    - bot-overview.md
    - bot-configuration.md
    - bot-commands.md

markdown_extensions:
  - smarty
  - toc:
      permalink: True
  - sane_lists
  - abbr
  - attr_list
  - def_list
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets
  - pymdownx.tilde

plugins:
  - search
  - git-authors
  - git-revision-date-localized
  - img2fig
  - navtitles
  - mermaid2

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js